Blog.web/Controllers/AdminBlogPostsController.cs
using Blog.web.Data;
using Blog.web.Models.Domain;
using Blog.web.Models.ViewModels;
using Blog.web.Repositories;
using Bloggie.Web.Models.Domain;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Linq;

namespace Blog.web.Controllers
{
    public class AdminBlogPostsController : Controller
    {
        private readonly ITagRepository tagRepository;
        private readonly BloggieDbContext bloggieDbContext;
        public AdminBlogPostsController(ITagRepository tagRepository, BloggieDbContext bloggieDbContext)
        {
            this.tagRepository = tagRepository;
            this.bloggieDbContext = bloggieDbContext;
        }
        [HttpGet]
        public IActionResult Add()
        {
            
            var tags = bloggieDbContext.Tags.ToList();
            var model = new AddBlogPostRequest {
               Tags = tags.Select(x=>new SelectListItem { Text = x.DisplayName, Value = x.Id.ToString()})
               
            };

            return View(model);
        }
        [HttpPost]
        public IActionResult Add(AddBlogPostRequest addBlogPostRequest)
        {
            //Console.WriteLine(addBlogPostRequest.SelectedTag);
            var selectedTags = new List<Tag>();

            foreach (var selectedTagId in addBlogPostRequest.SelectedTags)
            {
                var selectedTagIdGuid = Guid.Parse(selectedTagId);
                var existingTag = bloggieDbContext.Tags.Find(selectedTagIdGuid);

                if (existingTag != null)
                {
                    selectedTags.Add(existingTag);
                }
            }
            var blogPost = new BlogPost
            {
                Heading = addBlogPostRequest.Heading,
                PageTitle = addBlogPostRequest.PageTitle,
                Content = addBlogPostRequest.Content,
                ShortDescription  = addBlogPostRequest.ShortDescription,
                FeaturedImageUrl  = addBlogPostRequest.FeaturedImageUrl,
                UrlHandle = addBlogPostRequest.UrlHandle,
                PublishedDate = addBlogPostRequest.PublishedDate,
                Author = addBlogPostRequest.Author,
                visible = addBlogPostRequest.Visible,
                Tags = selectedTags

            };

            bloggieDbContext.Add(blogPost);
            bloggieDbContext.SaveChanges();
            return View("Add");
        }
        [HttpGet]
        public IActionResult List()
        {
            var listOfBlogs = bloggieDbContext.BlogPosts.ToList();
            ListBlogRequest blogs = new ListBlogRequest(listOfBlogs);
            return View(blogs);
        }
    }
}

Blog.web/Controllers/AdminTagsController.cs
using Blog.web.Data;
using Blog.web.Models.ViewModels;
using Blog.web.Repositories;
using Bloggie.Web.Models.Domain;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Identity.Client;

namespace Blog.web.Controllers
{
    public class AdminTagsController : Controller
    {
        private readonly BloggieDbContext _bloggieDbContext;
        private readonly ITagRepository tagRepository;
        public AdminTagsController(BloggieDbContext bloggieDbContext,ITagRepository tagRepository)
        {
                _bloggieDbContext = bloggieDbContext;
                this.tagRepository = tagRepository;
        }
        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Add(AddTagRequest addTagRequest)
        {
            //mapping the addTagRequest to the tag domain model
            var tag = new Tag {
                Name = addTagRequest.Name,
                DisplayName = addTagRequest.DisplayName
            };
           // _bloggieDbContext.Tags.Add(tag);
           //_bloggieDbContext.SaveChanges();
            tagRepository.AddTag(tag);
            return View("Add");
        }
        [HttpGet]
        public IActionResult List() {
            var tags = _bloggieDbContext.Tags.ToList();
            ListTagRequest parameterTags = new ListTagRequest(tags);
            foreach (var tag in tags)
            {
                Console.WriteLine(tag.Name);
            }
            return View(parameterTags);
        }
        [HttpGet]
        public IActionResult Edit(Guid id)
        {
            var tag = _bloggieDbContext.Tags.Find(id);
            Console.WriteLine($"{id.ToString()}");

            if(tag != null)
            {
                var editTagRequest = new EditTagRequest { 
                    Id = tag.Id,
                    Name = tag.Name,
                    DisplayName = tag.DisplayName 
                };
                return View(editTagRequest);
            }
            
            return View(null);
        }

        [HttpPost]
        public IActionResult Edit(EditTagRequest editTagRequest)
        {
            var tag = new Tag
            {
                Id = editTagRequest.Id,
                Name = editTagRequest.Name,
                DisplayName = editTagRequest.DisplayName
            };

            var existingTag = _bloggieDbContext.Tags.Find(tag.Id);
            if(existingTag != null)
            {
                existingTag.Name = tag.Name;
                existingTag.DisplayName = tag.DisplayName;

                _bloggieDbContext.SaveChanges();
                //show success
                return RedirectToAction("List");
            }
            else
            {
                Console.WriteLine("NULL tag");
            }
            //show failure
            return RedirectToAction("Edit", new {id = editTagRequest.Id });

        }
    }
}

Blog.web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Blog.web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Blog.web.styles.css" asp-append-version="true" />
    <link href='https://cdn.jsdelivr.net/npm/froala-editor@latest/css/froala_editor.pkgd.min.css' rel='stylesheet' type='text/css' />

    <script type='text/javascript' src='https://cdn.jsdelivr.net/npm/froala-editor@latest/js/froala_editor.pkgd.min.js'></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Blog.web</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Dropdown
                            </a>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item" asp-area="" asp-controller="AdminTags" asp-action="Add">Add</a></li>
                                <li><a class="dropdown-item" asp-area="" asp-controller="AdminTags" asp-action="List">List Tags</a></li>
                                <li><a class="dropdown-item" asp-area="" asp-controller="AdminBlogPosts" asp-action="Add">Add Posts</a></li>
                                <li><a class="dropdown-item" asp-area="" asp-controller="AdminBlogPosts" asp-action="List">List Posts</a></li>
                               
                            </ul>
                        </li>


                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Blog.web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>